config/routes.rb
Rails.application.routes.draw do

  # Dashboard routes
  get "home", to: "home#index"

  # Admins routes
  get "admin/new", to: "admins#new"
  # get     'admin/:username'     , to: 'admins#show'        , as: 'admin'
  post "admin/new", to: "admins#create"
  get "admin/:username/profile", to: "admins#edit", as: "edit_admin"
  put "admin/:username/profile", to: "admins#update"
  patch "admin/:username/profile", to: "admins#update"

  # Students routes
  get "admin/classrooms/:classroom_id/students/:student_id", to: "students#show", as: "student"
  get "signup", to: "students#new", as: "students_signup"
  post "signup", to: "students#create"
  get ":username/profile/", to: "students#edit", as: "edit_student"
  put ":username/profile/", to: "students#update"
  patch ":username/profile/", to: "students#update"
  patch "admin/classrooms/:classroom_id/students/:student_id/activate", to: "students#activate", as: "activate_student"
  patch "admin/classrooms/:classroom_id/students/:student_id/deactivate", to: "students#deactivate", as: "deactivate_student"
  delete "admin/classrooms/:classroom_id/students/:student_id/delete", to: "students#destroy", as: "destroy_student"

  #
  # For future implementation
  #

  # Reviewers routes
  # get     'admin/reviewers/:username'     , to: 'reviewers#show'       , as: 'reviewer'
  # get     'admin/reviewers'               , to: 'reviewers#index'      , as: 'reviewers'
  # get     'reviewers/signup'              , to: 'reviewers#new'
  # post    'reviewers/signup'              , to: 'reviewers#create'
  # get     'reviewers/:username/profile'    , to: 'reviewers#edit'       , as: 'reviewer_edit'
  # put     'reviewers/:username/profile/'      , to: 'reviewers#update'
  # patch   'reviewers/:username/profile/'      , to: 'reviewers#update'
  # patch   'reviewers/:id/activate/'       , to: 'reviewers#activate'   , as: 'activate_reviewer'
  # patch   'reviewers/:id/deactivate/'     , to: 'reviewers#deactivate' , as: 'deactivate_reviewer'
  # delete  'reviewers/:id/delete'          , to: 'reviewers#destroy'    , as: 'destroy_reviewer'

  # User Activation routes
  get "user_verification/:token/edit", to: "user_verifications#edit", as: "edit_user_verification"

  # Password Recovery routes
  get "password_reset", to: "password_resets#new", as: "password_reset"
  post "password_reset", to: "password_resets#create"
  get "password_reset/:token/edit", to: "password_resets#edit", as: "edit_password_reset"
  put "password_reset/:token/edit", to: "password_resets#update"
  patch "password_reset/:token/edit", to: "password_resets#update"

  # Sessions routes
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#leave"
  delete "logout", to: "sessions#destroy"

  # Addresses routes
  resources :addresses, path: "admin/addresses"

  # Schools routes
  resources :schools, path: "admin/schools"

  # Categories routes
  resources :categories, path: "admin/categories"

  # Themes routes
  resources :themes, path: "admin/themes"

  # Competences routes
  resources :competences, path: "admin/categories/:category/competences/", except: [:index, :show,:destroy]

  # Comments routes
  # resources :comments, path: "admin/categories/:category/competence/:competence/comments", except: [:index, :show, :destroy]

  # Classrooms routes
  resources :classrooms, path: "admin/classrooms", except: [:destroy]
  post :classrooms, path: "admin/classroom/:id/upload", to: "classrooms#new_file", as: "file_upload_classroom"
  delete :classrooms, path: "admin/classroom/:id/purge/:file_id", to: "classrooms#purge_file", as: "file_purge_classroom"

  # Submissions (Essays + Corrections) routes
  get "submissions", to: "submissions#index", as: "submissions"

  # Essays routes
  get "essays", to: "essays#index", as: "essays"
  post "essays", to: "essays#create"
  get "essays/essay_file", to: "essays#download", as: "download_essay_model"
  get "essays/send/", to: "essays#new", as: "new_essay"
  get "essays/send/:theme_hash_id", to: "essays#submit", as: "submit_essay"
  delete "essays/:essay_hash_id", to: "essays#destroy", as: "destroy_essay"

  # Corrections routes
  get "corrections", to: "corrections#index", as: "corrections"
  get "corrections/new", to: "corrections#new", as: "new_correction"
  get "corrections/:correction_hash_id", to: "corrections#show", as: "show_correction"
  get "corrections/:essay_hash_id/validate", to: "corrections#validate", as: "validate_correction"
  post "corrections/:essay_hash_id/", to: "corrections#create", as: "create_correction"
  get "corrections/:correction_hash_id/start", to: "corrections#start", as: "start_correction"
  patch "corrections/:correction_hash_id/", to: "corrections#update", as: "update_correction"
  post "corrections/:correction_hash_id/finish", to: "corrections#finish", as: "finish_correction"
  delete "corrections/:correction_hash_id/destroy", to: "corrections#destroy", as: "destroy_correction"

  # Correction Comments routes
  patch "corrections/:id/comment/update", to: "correction_comments#update", as: "update_correction_comment"
  delete "corrections/:id/comment/delete", to: "correction_comments#destroy", as: "destroy_correction_comment"

  # Credits routes
  get ":user_id/credits/refill", to: "credits#edit", as: "edit_credits"
  patch ":user_id/credits/refill", to: "credits#update", as: "update_credits"

  # Root
  root "sessions#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admins/edit.html.erb
<div class="row">
    <div class="col-md-12">
        <div class="card shadow-sm mb-3 text-dark">
            <h5 class="card-header">Editar Perfil</h5>
            <div class="card-body row">
                <div class="col-3 border-right border-black">
                    <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
                        <a class="nav-link active" data-toggle="pill" href="#basic" role="tab" aria-controls="basic"
                            aria-selected="true">Conta</a>
                        <a class="nav-link" data-toggle="pill" href="#security" role="tab" aria-controls="security"
                            aria-selected="false">Segurança</a>
                        <a class="nav-link" data-toggle="pill" href="#personal" role="tab" aria-controls="personal"
                            aria-selected="false">Pessoal</a>
                    </div>
                </div>
                <div class="col-9">
                    <%= form_with model: @admin, url: edit_admin_path(@admin.user.name.delete(' ')), local: true, id: "update_form",
                    class: 'flex-fill tab-content' do |f| %>
                    <%= f.fields_for :user do |user_field| %>
                    <div class="tab-pane fade show active" id="basic" role="tabpanel" aria-labelledby="basic-tab">
                        <div class="form-group">
                            <%= user_field.label :email, 'Email:' %>
                            <%= user_field.text_field :email, class: "form-control", placeholder: "Email", autocomplete: "off" %>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="security" role="tabpanel" aria-labelledby="security-tab">
                        <div class="form-group">
                            <%= user_field.label :password, 'Senha:' %>
                            <%= user_field.password_field :password, class: "form-control", placeholder: "*********" %>
                        </div>
                        <div class="form-group">
                            <%= user_field.label :password_confirmation, 'Confirmar Senha:' %>
                            <%= user_field.password_field :password_confirmation, class: "form-control", placeholder: "*********" %>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="personal" role="tabpanel" aria-labelledby="personal-tab">
                        <div class="form-group">
                            <%= user_field.label :name, 'Nome:' %>
                            <%= user_field.text_field :name, class: "form-control", placeholder: "Name", autocomplete: "off" %>
                        </div>
                        <div class="form-group">
                            <%= user_field.label :birth_date, 'Data de Nascimento:' %>
                            <%= user_field.date_field :birth_date, class: "form-control", placeholder: "Birth Date", autocomplete: "off" %>
                        </div>
                        <div class="form-group">
                            <%= user_field.label :cpf, 'CPF:' %>
                            <%= user_field.text_field :cpf, class: "form-control", placeholder: "CPF", autocomplete: "off" %>
                        </div>
                        <div class="form-group">
                            <%= user_field.label :address_id, 'Cidade:' %>
                            <%= user_field.select 'address_id', @address_options ,{ include_blank: 'Selecione a cidade...'},
                            class: "form-control custom-select" %>
                        </div>
                    </div>
                    <% end %>

                    <% end %>
                </div>
                <div class="col-12 d-flex justify-content-center mt-3">
                    <input type="submit" value="Salvar" form="update_form" name="commit"
                        class="btn btn-outline-primary" />
                </div>
            </div>
        </div>
    </div>
</div>

app/views/admins/home.html.erb
<div class="row">
    <div class="col-md-6">
        <div class="card mb-3 text-dark shadow-sm">
            <div class="card-body">
                <h5 class="card-title">Redações Recebidas</h5>
                <h3 class="card-text"><%= @essays.length %></h3>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card mb-3 text-dark shadow-sm">
            <div class="card-body">
                <h5 class="card-title">Redações Corrigidas</h5>
                <h3 class="card-text"><%= @corrected.length %></h3>
            </div>
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="card mb-3 text-dark shadow-sm">
            <div class="card-body">
                <h5 class="card-title">Alunos Ativos</h5>
                <h3 class="card-text"><%= @students.length %></h3>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card mb-3 text-dark shadow-sm">
            <div class="card-body">
                <h5 class="card-title">Categorias dos Alunos</h5>
                <div class="row">
                    <div class="col-md-6">
                        <h3 class="card-text"><strong class="text-primary">ENEM:</strong> <%= @enem.length %></h3>
                    </div>
                    <div class="col-md-6">
                        <h3 class="card-text"><strong class="text-primary">IFRN:</strong> <%= @ifrn.length %></h3>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card mb-3 text-dark shadow-sm">
            <div class="card-body">
                <h5 class="card-title">Correções Ativas</h5>
                <div class="table-responsive-md">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Tema</th>
                                <th>Autor</th>
                                <th>Data de Início</th>
                                <th>Iniciada por</th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @correcting.each do |correction| %>
                            <tr>
                                <td class="align-middle"><%= correction.essay.theme.description %></td>
                                <td class="align-middle"><%= correction.student.user.username %></td>
                                <td class="align-middle"><%= correction.start_date.strftime("%d/%m/%Y") %></td>
                                <% if correction.admin %>
                                <td class="align-middle"><%= correction.admin.user.username %></td>
                                <% else %>
                                <td class="align-middle"><%= correction.reviewer.user.username %></td>
                                <% end %>
                                <td class="align-middle">
                                    <%= link_to start_correction_path(correction.hash_id), class: "btn btn-link" do %>
                                    <span data-toggle="tooltip" data-placement="top" title="Continuar Correção">
                                        <%= fa_icon 'pencil-alt' %>
                                    </span>
                                    <% end %>
                                </td>
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card mb-3 text-dark shadow-sm">
            <div class="card-body">
                <div class="row mb-2">
                    <div class="col-md-6 d-flex">
                        <h5 class="card-title mb-0 align-self-center">Correções Finalizadas</h5>
                    </div>
                    <div class="col-md-6 d-flex justify-content-end">
                        <%= link_to new_correction_path, class: "btn btn-link card-link" do %>
                        <span>Nova Correção</span>
                        <% end %>
                    </div>
                </div>
                <div class="table-responsive-md">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Tema</th>
                                <th>Autor</th>
                                <th>Data de Início</th>
                                <th>Data de Conclusão</th>
                                <th>Corrigida por</th>
                                <th>Pontuação</th>

                            </tr>
                        </thead>
                        <tbody>
                            <% @corrected.each do |correction| %>
                            <tr>
                                <td class="align-middle"><%= correction.essay.theme.description %></td>
                                <td class="align-middle"><%= correction.student.user.username %></td>
                                <td class="align-middle"><%= correction.start_date.strftime("%d/%m/%Y") %></td>
                                <td class="align-middle"><%= correction.end_date.strftime("%d/%m/%Y") %></td>
                                <% if correction.admin %>
                                <td class="align-middle"><%= correction.admin.user.username %></td>
                                <% else %>
                                <td class="align-middle"><%= correction.reviewer.user.username %></td>
                                <% end %>
                                <td class="align-middle"><%= correction.final_score %></td>
                                <td class="align-middle">
                                    <% if correction.valid_essay %>
                                    <%= link_to show_correction_path(correction.hash_id), class: "btn btn-link" do %>
                                    <span data-toggle="tooltip" data-placement="top" title="Detalhes">
                                        <%= fa_icon 'eye' %>
                                    </span>
                                    <% end %>
                                    <% else %>
                                    <small class="text-danger">Inválida!</small>
                                    <% end %>
                                </td>
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/admins/new.html.erb
<div class="row">
    <div class="col-md-12">
        <div class="card mb-3 shadow-sm text-dark">
            <div class="card-body">
                <h5 class="card-title">Novo Admin</h5>
                <%= form_with(model: @admin, url: admin_new_path, class: "d-flex flex-column", local: true) do |f| %>
                    <%= f.fields_for :user do |user_field| %>
                    <div class="form-group"> 
                        <%= user_field.label :email, 'Email:' %>
                        <%= user_field.text_field :email, autocomplete: "off", class: "form-control" %>
                        <span class="text-danger"><%= @admin.user.errors.messages[:email].first if @admin.errors.any? %></span>
                    </div>
                    <div class="form-group"> 
                        <%= user_field.label :username, 'Username:' %>
                        <%= user_field.text_field :username, autocomplete: "off", class: "form-control" %>
                        <span class="text-danger"><%= @admin.user.errors.messages[:username].first if @admin.errors.any? %></span>
                    </div>
                    <div class="form-group">
                        <%= user_field.label :password, 'Senha:' %>
                        <%= user_field.password_field :password, class: "form-control" %>
                        <span class="text-danger"><%= @admin.user.errors.messages[:password].first if @admin.errors.any? %></span>
                    </div>
                    <div class="form-group">
                        <%= user_field.label :password_confirmation, 'Confirmar senha:' %>
                        <%= user_field.password_field :password_confirmation, class: "form-control" %>
                        <span class="text-danger"><%= @admin.user.errors.messages[:password_confirmation].first if @admin.errors.any? %></span>
                    </div>
                    <div class="form-group">
                        <%= user_field.label :name, 'Name' %>
                        <%= user_field.text_field :name, autocomplete: "off", class: "form-control" %>
                        <span class="text-danger"><%= @admin.user.errors.messages[:name].first if @admin.errors.any? %></span>
                    </div>
                    <div class="form-group">
                        <%= user_field.label :birth_date, 'Birth Date' %>
                        <%= user_field.date_field :birth_date, autocomplete: "off", class: "form-control" %>
                        <span class="text-danger"><%= @admin.user.errors.messages[:birth_date].first if @admin.errors.any? %></span>
                    </div>
                    <div class="form-group">
                        <%= user_field.label :cpf, 'CPF' %>
                        <%= user_field.text_field :cpf, autocomplete: "off", class: "form-control" %>
                        <span class="text-danger"><%= @admin.user.errors.messages[:cpf].first if @admin.errors.any? %></span>
                    </div>
                    
                    <div class="form-group">
                        <%= user_field.label :address_id, 'City' %>
                        <%= user_field.select 'address_id', @address_options ,{ include_blank: 'Selecione a cidade...'}, class: "form-control custom-select" %>
                        <span class="text-danger"><%= @admin.user.errors.messages[:address].first if @admin.errors.any? %></span>
                    </div>
                    <% end %>

                    <div class="form-group align-self-center">
                        <%= f.submit class: "btn btn-primary mr-2" do%>
                        <span>Cadastrar</span>
                        <% end %>

                        <%= link_to home_path, class: "btn btn-primary mr-2" do %>
                        <span>Cancelar</span>
                        <% end %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

<% if @admin.errors.any? %>
<script>

    $(".form-group input, .form-group select").each(function () {
        $(this).removeClass("border-dark").addClass("border-danger");
    })

</script>
<% end %>