config/routes.rb
Rails.application.routes.draw do

  # Dashboard routes
  get "home", to: "home#index"

  # Admins routes
  get "admin/new", to: "admins#new"
  # get     'admin/:username'     , to: 'admins#show'        , as: 'admin'
  post "admin/new", to: "admins#create"
  get "admin/:username/profile", to: "admins#edit", as: "edit_admin"
  put "admin/:username/profile", to: "admins#update"
  patch "admin/:username/profile", to: "admins#update"

  # Students routes
  get "admin/classrooms/:classroom_id/students/:student_id", to: "students#show", as: "student"
  get "signup", to: "students#new", as: "students_signup"
  post "signup", to: "students#create"
  get ":username/profile/", to: "students#edit", as: "edit_student"
  put ":username/profile/", to: "students#update"
  patch ":username/profile/", to: "students#update"
  patch "admin/classrooms/:classroom_id/students/:student_id/activate", to: "students#activate", as: "activate_student"
  patch "admin/classrooms/:classroom_id/students/:student_id/deactivate", to: "students#deactivate", as: "deactivate_student"
  delete "admin/classrooms/:classroom_id/students/:student_id/delete", to: "students#destroy", as: "destroy_student"

  #
  # For future implementation
  #

  # Reviewers routes
  # get     'admin/reviewers/:username'     , to: 'reviewers#show'       , as: 'reviewer'
  # get     'admin/reviewers'               , to: 'reviewers#index'      , as: 'reviewers'
  # get     'reviewers/signup'              , to: 'reviewers#new'
  # post    'reviewers/signup'              , to: 'reviewers#create'
  # get     'reviewers/:username/profile'    , to: 'reviewers#edit'       , as: 'reviewer_edit'
  # put     'reviewers/:username/profile/'      , to: 'reviewers#update'
  # patch   'reviewers/:username/profile/'      , to: 'reviewers#update'
  # patch   'reviewers/:id/activate/'       , to: 'reviewers#activate'   , as: 'activate_reviewer'
  # patch   'reviewers/:id/deactivate/'     , to: 'reviewers#deactivate' , as: 'deactivate_reviewer'
  # delete  'reviewers/:id/delete'          , to: 'reviewers#destroy'    , as: 'destroy_reviewer'

  # User Activation routes
  get "user_verification/:token/edit", to: "user_verifications#edit", as: "edit_user_verification"

  # Password Recovery routes
  get "password_reset", to: "password_resets#new", as: "password_reset"
  post "password_reset", to: "password_resets#create"
  get "password_reset/:token/edit", to: "password_resets#edit", as: "edit_password_reset"
  put "password_reset/:token/edit", to: "password_resets#update"
  patch "password_reset/:token/edit", to: "password_resets#update"

  # Sessions routes
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#leave"
  delete "logout", to: "sessions#destroy"

  # Addresses routes
  resources :addresses, path: "admin/addresses"

  # Schools routes
  resources :schools, path: "admin/schools"

  # Categories routes
  resources :categories, path: "admin/categories"

  # Themes routes
  resources :themes, path: "admin/themes"

  # Competences routes
  resources :competences, path: "admin/categories/:category/competences/", except: [:index, :show,:destroy]

  # Comments routes
  # resources :comments, path: "admin/categories/:category/competence/:competence/comments", except: [:index, :show, :destroy]

  # Classrooms routes
  resources :classrooms, path: "admin/classrooms", except: [:destroy]
  post :classrooms, path: "admin/classroom/:id/upload", to: "classrooms#new_file", as: "file_upload_classroom"
  delete :classrooms, path: "admin/classroom/:id/purge/:file_id", to: "classrooms#purge_file", as: "file_purge_classroom"

  # Submissions (Essays + Corrections) routes
  get "submissions", to: "submissions#index", as: "submissions"

  # Essays routes
  get "essays", to: "essays#index", as: "essays"
  post "essays", to: "essays#create"
  get "essays/essay_file", to: "essays#download", as: "download_essay_model"
  get "essays/send/", to: "essays#new", as: "new_essay"
  get "essays/send/:theme_hash_id", to: "essays#submit", as: "submit_essay"
  delete "essays/:essay_hash_id", to: "essays#destroy", as: "destroy_essay"

  # Corrections routes
  get "corrections", to: "corrections#index", as: "corrections"
  get "corrections/new", to: "corrections#new", as: "new_correction"
  get "corrections/:correction_hash_id", to: "corrections#show", as: "show_correction"
  get "corrections/:essay_hash_id/validate", to: "corrections#validate", as: "validate_correction"
  post "corrections/:essay_hash_id/", to: "corrections#create", as: "create_correction"
  get "corrections/:correction_hash_id/start", to: "corrections#start", as: "start_correction"
  patch "corrections/:correction_hash_id/", to: "corrections#update", as: "update_correction"
  post "corrections/:correction_hash_id/finish", to: "corrections#finish", as: "finish_correction"
  delete "corrections/:correction_hash_id/destroy", to: "corrections#destroy", as: "destroy_correction"

  # Correction Comments routes
  patch "corrections/:id/comment/update", to: "correction_comments#update", as: "update_correction_comment"
  delete "corrections/:id/comment/delete", to: "correction_comments#destroy", as: "destroy_correction_comment"

  # Credits routes
  get ":user_id/credits/refill", to: "credits#edit", as: "edit_credits"
  patch ":user_id/credits/refill", to: "credits#update", as: "update_credits"

  # Root
  root "sessions#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  after_create :create_registration_number

  has_many :corrections, dependent: :destroy
  has_many :essays, dependent: :destroy
  belongs_to :user, dependent: :destroy
  belongs_to :category
  belongs_to :school
  belongs_to :classroom

  accepts_nested_attributes_for :user

  validates :user, :school, :category, :classroom, presence: true
  validates :registration_number, length: { maximum: 10 }
  validates :credits, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def refill_credits(amount)
    self.credits += amount unless amount == 0
  end

  # private

  def create_registration_number
    self.registration_number = (Date.current.year.to_s +
                               ((sprintf "%03d", self.classroom.id).to_s) +
                               (sprintf "%03d", self.id).to_s).to_s

    self.save
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  layout "login", only: [:new, :create]
  before_action :require_logout, only: [:new, :create]
  before_action :require_login, only: [:index, :show, :edit, :update, :activate, :deactivate, :destroy]
  before_action :require_admin, only: [:index, :show, :deactivate, :activate, :destroy]
  before_action :require_student, only: [:edit, :update]
  before_action :address_options, :school_options, :classroom_options, :category_options, only: [:new, :create, :edit, :update]
  before_action :set_student, except: [:index, :new, :create]

  def index
    @students = Student.includes(:category, :school, user: :address).paginate(page: params[:page], per_page: 16)
      .where(users: { verified: true })
  end

  def show
  end

  def new
    @student = Student.new
    @student.build_user
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      @student.user.send_verification_email
      redirect_to root_path, info: "Link de verificação enviado, consulte seu email para obtê-lo"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @student.update(student_params)
      redirect_to edit_student_path(@student.user.username.delete(" ").downcase), success: "Perfil atualizado com sucesso"
    else
      flash.now[:error] = "Erro ao atualizar perfil"
      render :edit
    end
  end

  def activate
    unless @student.user.active?
      @student.user.toggle(:active)
      redirect_to home_path, error: "Erro ao ativar usuário" unless @student.save
      redirect_to classroom_path(@student.classroom)
    end
  end

  def deactivate
    if @student.user.active?
      @student.user.toggle(:active)
      redirect_to home_path, error: "Erro ao desativar usuário" unless @student.save
      redirect_to classroom_path(@student.classroom)
    end
  end

  def destroy
    @student.destroy
    redirect_to classroom_path(@student.classroom), success: "Aluno removido com sucesso"
  end

  private

  def set_student
    @student = current_user.student || Student.find_by(id: params[:student_id])
  end

  def student_params
    params.require(:student).permit(:classroom_id, :school_id, :category_id, user_attributes: [:id, :email, :username, :password, :password_confirmation,
                                                                                :name, :birth_date, :cpf, :address_id])
  end

  def address_options
    @address_options = Address.all.pluck(:city, :id)
  end

  def category_options
    @category_options = Category.all.pluck(:description, :id)
  end

  def school_options
    @school_options = School.all.pluck(:name, :id)
  end

  def classroom_options
    @classroom_options = Classroom.all.pluck(:name, :id)
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/edit.html.erb
<div class="row">
    <div class="col-md-12">
        <div class="card shadow-sm mb-3 text-dark">
            <h5 class="card-header">Editar Perfil</h5>
            <div class="card-body row">
                <div class="col-3 border-right border-black">
                    <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
                        <a class="nav-link active" data-toggle="pill" href="#basic" role="tab" aria-controls="basic"
                            aria-selected="true">Conta</a>
                        <a class="nav-link" data-toggle="pill" href="#security" role="tab" aria-controls="security"
                            aria-selected="false">Segurança</a>
                        <a class="nav-link" data-toggle="pill" href="#personal" role="tab" aria-controls="personal"
                            aria-selected="false">Pessoal</a>
                        <a class="nav-link" data-toggle="pill" href="#scholarity" role="tab" aria-controls="scholarity"
                            aria-selected="false">Escolaridade</a>
                        <a class="nav-link" data-toggle="pill" href="#category" role="tab" aria-controls="category"
                            aria-selected="false">Categoria</a>
                        <a class="nav-link" data-toggle="pill" href="#classroom" role="tab" aria-controls="classroom"
                            aria-selected="false">Turma</a>
                    </div>
                </div>
                <div class="col-9">
                    <%= form_with model: @student, url: edit_student_path(@student.user.name.delete(' ')), local: true, id: "update_form",
                    class: 'flex-fill tab-content' do |f| %>
                    <%= f.fields_for :user do |user_field| %>
                    <div class="tab-pane fade show active" id="basic" role="tabpanel" aria-labelledby="basic-tab">
                        <div class="form-group">
                            <%= user_field.label :email, 'Email:' %>
                            <%= user_field.text_field :email, class: "form-control", placeholder: "Email", autocomplete: "off" %>
                            <span
                                class="text-danger"><%= @student.user.errors.messages[:email].first if @student.errors.any? %></span>
                        </div>
                        <div class="form-group">
                            <%= user_field.label :username, 'Username:' %>
                            <%= user_field.text_field :username, class: "form-control", placeholder: "Username", autocomplete: "off" %>
                            <span
                                class="text-danger"><%= @student.user.errors.messages[:username].first if @student.errors.any? %></span>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="security" role="tabpanel" aria-labelledby="security-tab">
                        <div class="form-group">
                            <%= user_field.label :password, 'Senha:' %>
                            <%= user_field.password_field :password, class: "form-control", placeholder: "*********" %>
                            <span
                                class="text-danger"><%= @student.user.errors.messages[:password].first if @student.errors.any? %></span>

                        </div>
                        <div class="form-group">
                            <%= user_field.label :password_confirmation, 'Confirmar Senha:' %>
                            <%= user_field.password_field :password_confirmation, class: "form-control", placeholder: "*********" %>
                            <span
                                class="text-danger"><%= @student.user.errors.messages[:password_confirmation].first if @student.errors.any? %></span>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="personal" role="tabpanel" aria-labelledby="personal-tab">
                        <div class="form-group">
                            <%= user_field.label :name, 'Nome:' %>
                            <%= user_field.text_field :name, class: "form-control", placeholder: "Name", autocomplete: "off" %>
                            <span
                                class="text-danger"><%= @student.user.errors.messages[:name].first if @student.errors.any? %></span>

                        </div>
                        <div class="form-group">
                            <%= user_field.label :birth_date, 'Data de Nascimento:' %>
                            <%= user_field.date_field :birth_date, class: "form-control", placeholder: "Birth Date", autocomplete: "off" %>
                            <span
                                class="text-danger"><%= @student.user.errors.messages[:birth_date].first if @student.errors.any? %></span>

                        </div>
                        <div class="form-group">
                            <%= user_field.label :cpf, 'CPF:' %>
                            <%= user_field.text_field :cpf, class: "form-control", placeholder: "CPF", autocomplete: "off" %>
                            <span
                                class="text-danger"><%= @student.user.errors.messages[:cpf].first if @student.errors.any? %></span>
                        </div>
                        <div class="form-group">
                            <%= user_field.label :address_id, 'Cidade:' %>
                            <%= user_field.select 'address_id', @address_options ,{ include_blank: 'Selecione a cidade...'},
                            class: "form-control custom-select" %>
                            <span
                                class="text-danger"><%= @student.user.errors.messages[:address].first if @student.errors.any? %></span>
                        </div>
                    </div>
                    <% end %>

                    <div class="tab-pane fade" id="scholarity" role="tabpanel" aria-labelledby="scholarity-tab">
                        <div class="form-group">
                            <%= f.label :school_id, 'Escola:' %>
                            <%= f.select 'school_id', @school_options ,{ include_blank: 'Selecione a escola...'},
                            class: "form-control custom-select" %>
                            <span
                                class="text-danger"><%= @student.errors.messages[:school].first if @student.errors.any? %></span>
                        </div>

                    </div>
                    <div class="tab-pane fade" id="category" role="tabpanel" aria-labelledby="category-tab">
                        <div class="form-group">
                            <%= f.label :category_id, 'Categoria:' %>
                            <%= f.select 'category_id', @category_options ,{ include_blank: 'Selecione a categoria...'},
                            class: "form-control custom-select" %>
                            <span
                                class="text-danger"><%= @student.errors.messages[:category].first if @student.errors.any? %></span>
                        </div>
                    </div>

                    <div class="tab-pane fade" id="classroom" role="tabpanel" aria-labelledby="classroom-tab">
                        <div class="form-group">
                            <%= f.label :classroom_id, 'Turma:' %>
                            <%= f.select 'classroom_id', @classroom_options ,{ include_blank: 'Selecione a turma...'},
                                                    class: "form-control custom-select" %>
                            <span
                                class="text-danger"><%= @student.errors.messages[:category].first if @student.errors.any? %></span>
                        </div>
                    </div>
                    <% end %>
                </div>
                <div class="col-12 d-flex justify-content-center mt-3">
                    <input type="submit" value="Salvar" form="update_form" name="commit"
                        class="btn btn-outline-primary">
                </div>
            </div>
        </div>
    </div>
</div>

<% if @student.errors.any? %>
<script>

    $(".form-group input, .form-group select").each(function () {
        $(this).removeClass("border-dark").addClass("border-danger");
    })

</script>
<% end %>

app/views/students/home.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="row">
    <div class="col-md-6 ">
        <div class="card shadow-sm mb-3 text-dark">
            <div class="card-body">
                <h5 class="card-title">Redações Enviadas</h5>
                <h3 class="card-text"><%= current_user.student.submissions %></h3>
            </div>
        </div>
    </div>
    <div class="col-md-6 ">
        <div class="card shadow-sm mb-3">
            <div class="card-body">
                <h5 class="card-title">Redações Corrigidas</h5>
                <h3 class="card-text"><%= current_user.student.reviewed_submissions %></h3>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 ">
        <div class="card shadow-sm mb-3">
            <div class="card-body">
                <h5 class="card-title">Ultimas Submissões</h5>
                <div class="table-responsive-md">
                    <table class="table table-bordered table-striped  ">
                        <thead>
                            <tr>
                                <th>Tema</th>
                                <th>Corrigida em</th>
                                <th>Corrigida por</th>
                                <th>Pontuação</th>
                            </tr>
                        </thead>
                        <tbody>
                            <% get_student_finished_corrections(5).each do |correction| %>
                            <tr>
                                <td class="align-middle"><%= correction.essay.theme.description %></td>
                                <td class="align-middle"><%= correction.end_date.strftime("%d/%m/%Y") %></td>
                                <% if correction.admin %>
                                <td class="align-middle"><%= correction.admin.user.username %></td>
                                <% else %>
                                <td class="align-middle"><%= correction.reviewer.user.username %></td>
                                <% end %>
                                <td class="align-middle"><%= correction.final_score %></td>
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card mb-3 shadow-sm text-dark">
            <div class="card-body">
                <h5 class="card-title">Material</h5>
                <div class="table-responsive-md">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <th>Anexo</th>
                        </thead>
                        <tbody>
                            <% current_user.student.classroom.files.each do |file| %>
                            <tr>
                                <td class="align-middle"><%= file.blob.filename %></td>
                                <td class="align-middle">
                                    <%= link_to rails_blob_path(file, disposition: "attachment") do %>
                                    <span data-toggle="tooltip" data-placement="top" title="Download Anexo">
                                        <%= fa_icon 'file-download' %>
                                    </span>
                                    <% end %>
                                </td>
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

app/views/students/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card mb-3 text-dark shadow-sm">
      <div class="card-body overflow-auto">
        <h5 class="card-title">Alunos</h5>
        <div class="table-responsive-md">
          <table class="table table-bordered table-striped">
            <thead>
              <th class="text-center" style="width: 3%">Matrícula</th>
              <th style="width: 27%">Username</th>
              <th style="width: 23%">Email</th>
              <th style="width: 7%">Categoria</th>
              <th style="width: 5%">Créditos</th>
            </thead>
            <tbody>
              <% @students.each do |student| %>
              <tr>
                <td class="align-middle"><%= student.registration_number %></td>
                <td class="align-middle"><%= student.user.username %></td>
                <td class="align-middle"><%= student.user.email %></td>
                <td class="align-middle"><%= student.category.description %></td>
                <td class="align-middle"><%= student.credits %></td>
                <td class="align-middle">
                  <%= link_to student_path(student), class: "btn btn-link" do %>
                  <span data-toggle="tooltip" data-placement="top" title="Detalhes">
                    <%= fa_icon 'eye' %>
                  </span>
                  <% end %>

                  <%= link_to edit_credits_path(student), class: "btn btn-link" do %>
                  <span data-toggle="tooltip" data-placement="top" title="Adicionar Créditos">
                    <%= fa_icon 'donate' %>
                  </span>
                  <% end %>

                  <% if student.user.active %>
                  <%= link_to deactivate_student_path(student), method: 'patch', class: "btn btn-link" do %>
                  <span data-toggle="tooltip" data-placement="top" title="Desativar Usuário">
                    <%= fa_icon 'lightbulb' %>
                  </span>
                  <% end %>
                  <% else %>
                  <%= link_to activate_student_path(student), method: 'patch', class: "btn btn-link" do %>
                  <span data-toggle="tooltip" data-placement="top" title="Ativar Usuário">
                    <%= fa_icon 'lightbulb', type: :regular %>
                  </span>
                  <% end %>
                  <% end %>

                  <%= link_to destroy_student_path(student), method: 'delete', class: "btn btn-link" do %>
                  <span data-toggle="tooltip" data-placement="top" title="Remover">
                    <%= fa_icon 'trash' %>
                  </span>
                  <% end %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>

        <%= will_paginate @students, list_classes: %w(pagination justify-content-center),
                                        next_label: "&#62;", previous_label: "&#60;"  %>
      </div>
    </div>
  </div>
</div>

app/views/students/new.html.erb
<div class="card-header bg-white align-self-center">
    <h3 class="card-title">Criar conta</h3>
</div>


<div class="align-self-center flex-fill" style="width: 100%; padding: 15px 8px">
    <%= form_for @student, url: signup_path, html: 
    { class: "d-flex flex-column justify-content-around align-items-center",
      style: "height: 100%" } do |f| %>

    <%= f.fields_for :user do |user_field| %>
    <div class="field-div d-flex flex-column ">
        <%= user_field.label :email, 'Email', class: "input-label text-dark" %>
        <div class="input-div border-bottom border-dark d-flex">
            <%= user_field.text_field :email, placeholder: "Insira seu email", class: "border-0 flex-fill align-self-stretch", autocomplete: "off" %>
        </div>
        <span class="text-danger"><%= @student.user.errors.messages[:email].first if @student.errors.any? %></span>
    </div>

    <div class="field-div d-flex flex-column ">
        <%= user_field.label :username, 'Username', class: "input-label text-dark" %>
        <div class="input-div border-bottom border-dark d-flex">
            <%= user_field.text_field :username, placeholder: "Insira seu username", class: "border-0 flex-fill align-self-stretch", autocomplete: "off" %>
        </div>
        <span class="text-danger"><%= @student.user.errors.messages[:username].first if @student.errors.any? %></span>
    </div>

    <div class="field-div d-flex flex-column">
        <%= user_field.label :password, 'Senha', class: "input-label text-dark" %>
        <div class="input-div border-bottom border-dark d-flex">
            <%= user_field.password_field :password, placeholder: "Insira sua Senha", class: "border-0 flex-fill align-self-stretch"%>
        </div>
        <span class="text-danger"><%= @student.user.errors.messages[:password].first if @student.errors.any? %></span>
    </div>
    <div class="field-div d-flex flex-column">
        <%= user_field.label :password_confirmation, 'Confirmar Senha', class: "input-label text-dark" %>
        <div class="input-div border-bottom border-dark d-flex">
            <%= user_field.password_field :password_confirmation, placeholder: "Confirme sua senha", class: "border-0 flex-fill align-self-stretch" %>
        </div>
        <span
            class="text-danger"><%= @student.user.errors.messages[:password_confirmation].first if @student.errors.any? %></span>
    </div>
    <div class="field-div d-flex flex-column">
        <%= user_field.label :name, 'Nome', class: "input-label text-dark" %>
        <div class="input-div border-bottom border-dark d-flex">
            <%= user_field.text_field :name, placeholder: "Insira seu nome", class: "border-0 flex-fill align-self-stretch", autocomplete: "off" %>
        </div>
        <span class="text-danger"><%= @student.user.errors.messages[:name].first if @student.errors.any? %></span>
    </div>
    <div class="field-div d-flex flex-column">
        <%= user_field.label :birth_date, 'Data de Nascimento', class: "input-label text-dark" %>
        <div class="input-div border-bottom border-dark d-flex">
            <%= user_field.date_field :birth_date, placeholder: "Insira sua data de nascimento", class: "border-0 flex-fill align-self-stretch", autocomplete: "off" %>
        </div>
        <span class="text-danger"><%= @student.user.errors.messages[:birth_date].first if @student.errors.any? %></span>
    </div>
    <div class="field-div d-flex flex-column">
        <%= user_field.label :cpf, 'CPF', class: "input-label text-dark" %>
        <div class="input-div border-bottom border-dark d-flex">
            <%= user_field.text_field :cpf, placeholder: "Insira seu CPF", class: "border-0 flex-fill align-self-stretch", autocomplete: "off" %>
        </div>
        <span class="text-danger"><%= @student.user.errors.messages[:cpf].first if @student.errors.any? %></span>
    </div>
    
    <div class="field-div d-flex flex-column">
        <%= user_field.label :address_id, 'Cidade', class: "input-label text-dark" %>
        <div class="input-div border-bottom border-dark d-flex">
            <%= user_field.select 'address_id', @address_options ,{ include_blank: 'Selecione sua cidade...'},
            class: "custom-select border-0 flex-fill align-self-stretch",
            style: "box-shadow: none" %>
        </div>
        <span class="text-danger"><%= @student.user.errors.messages[:address].first if @student.errors.any? %></span>
    </div>
    <% end %>

    <div class="field-div d-flex flex-column">
        <%= f.label :classroom_id, 'Turma', class: "input-label text-dark"  %>
        <div class="input-div border-bottom border-dark d-flex">
            <%= f.select 'classroom_id', @classroom_options ,{ include_blank: 'Selecione sua turma...'},
            class: "custom-select border-0 flex-fill align-self-stretch",
            style: "box-shadow: none" %>
        </div>
        <span class="text-danger"><%= @student.errors.messages[:classroom].first if @student.errors.any? %></span>
    </div>

    <div class="field-div d-flex flex-column">
        <%= f.label :school_id, 'Escola', class: "input-label text-dark"  %>
        <div class="input-div border-bottom border-dark d-flex">
            <%= f.select 'school_id', @school_options ,{ include_blank: 'Selecione sua escola...'},
            class: "custom-select border-0 flex-fill align-self-stretch",
            style: "box-shadow: none" %>
        </div>
        <span class="text-danger"><%= @student.errors.messages[:school].first if @student.errors.any? %></span>
    </div>

    <div class="field-div d-flex flex-column">
        <%= f.label :category_id, 'Categoria', class: "input-label text-dark"  %>
        <div class="input-div border-bottom border-dark d-flex">
            <%= f.select 'category_id', @category_options ,{ include_blank: 'Selecione sua categoria...'},
            class: "custom-select border-0 flex-fill align-self-stretch",
            style: "box-shadow: none" %>
        </div>
        <span class="text-danger"><%= @student.errors.messages[:category].first if @student.errors.any? %></span>
    </div>

    <div class="submit-div" style="padding: 20px">
        <%= f.submit 'Criar conta', class: "btn btn-outline-primary btn-lg btn-inicial rounded-pill
        font-weight-bolder text-uppercase", 
        style: "padding: 10px 50px; border-width: 2px;" %>
    </div>

    <% end %>
</div>

<% if @student.errors.any? %>
<script>

    $("#new_student .input-div").each(function () {
        $(this).removeClass("border-dark").addClass("border-danger");
    })

</script>
<% end %>