config/routes.rb
Rails.application.routes.draw do

  # Dashboard routes
  get "home", to: "home#index"

  # Admins routes
  get "admin/new", to: "admins#new"
  # get     'admin/:username'     , to: 'admins#show'        , as: 'admin'
  post "admin/new", to: "admins#create"
  get "admin/:username/profile", to: "admins#edit", as: "edit_admin"
  put "admin/:username/profile", to: "admins#update"
  patch "admin/:username/profile", to: "admins#update"

  # Students routes
  get "admin/classrooms/:classroom_id/students/:student_id", to: "students#show", as: "student"
  get "signup", to: "students#new", as: "students_signup"
  post "signup", to: "students#create"
  get ":username/profile/", to: "students#edit", as: "edit_student"
  put ":username/profile/", to: "students#update"
  patch ":username/profile/", to: "students#update"
  patch "admin/classrooms/:classroom_id/students/:student_id/activate", to: "students#activate", as: "activate_student"
  patch "admin/classrooms/:classroom_id/students/:student_id/deactivate", to: "students#deactivate", as: "deactivate_student"
  delete "admin/classrooms/:classroom_id/students/:student_id/delete", to: "students#destroy", as: "destroy_student"

  #
  # For future implementation
  #

  # Reviewers routes
  # get     'admin/reviewers/:username'     , to: 'reviewers#show'       , as: 'reviewer'
  # get     'admin/reviewers'               , to: 'reviewers#index'      , as: 'reviewers'
  # get     'reviewers/signup'              , to: 'reviewers#new'
  # post    'reviewers/signup'              , to: 'reviewers#create'
  # get     'reviewers/:username/profile'    , to: 'reviewers#edit'       , as: 'reviewer_edit'
  # put     'reviewers/:username/profile/'      , to: 'reviewers#update'
  # patch   'reviewers/:username/profile/'      , to: 'reviewers#update'
  # patch   'reviewers/:id/activate/'       , to: 'reviewers#activate'   , as: 'activate_reviewer'
  # patch   'reviewers/:id/deactivate/'     , to: 'reviewers#deactivate' , as: 'deactivate_reviewer'
  # delete  'reviewers/:id/delete'          , to: 'reviewers#destroy'    , as: 'destroy_reviewer'

  # User Activation routes
  get "user_verification/:token/edit", to: "user_verifications#edit", as: "edit_user_verification"

  # Password Recovery routes
  get "password_reset", to: "password_resets#new", as: "password_reset"
  post "password_reset", to: "password_resets#create"
  get "password_reset/:token/edit", to: "password_resets#edit", as: "edit_password_reset"
  put "password_reset/:token/edit", to: "password_resets#update"
  patch "password_reset/:token/edit", to: "password_resets#update"

  # Sessions routes
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#leave"
  delete "logout", to: "sessions#destroy"

  # Addresses routes
  resources :addresses, path: "admin/addresses"

  # Schools routes
  resources :schools, path: "admin/schools"

  # Categories routes
  resources :categories, path: "admin/categories"

  # Themes routes
  resources :themes, path: "admin/themes"

  # Competences routes
  resources :competences, path: "admin/categories/:category/competences/", except: [:index, :show,:destroy]

  # Comments routes
  # resources :comments, path: "admin/categories/:category/competence/:competence/comments", except: [:index, :show, :destroy]

  # Classrooms routes
  resources :classrooms, path: "admin/classrooms", except: [:destroy]
  post :classrooms, path: "admin/classroom/:id/upload", to: "classrooms#new_file", as: "file_upload_classroom"
  delete :classrooms, path: "admin/classroom/:id/purge/:file_id", to: "classrooms#purge_file", as: "file_purge_classroom"

  # Submissions (Essays + Corrections) routes
  get "submissions", to: "submissions#index", as: "submissions"

  # Essays routes
  get "essays", to: "essays#index", as: "essays"
  post "essays", to: "essays#create"
  get "essays/essay_file", to: "essays#download", as: "download_essay_model"
  get "essays/send/", to: "essays#new", as: "new_essay"
  get "essays/send/:theme_hash_id", to: "essays#submit", as: "submit_essay"
  delete "essays/:essay_hash_id", to: "essays#destroy", as: "destroy_essay"

  # Corrections routes
  get "corrections", to: "corrections#index", as: "corrections"
  get "corrections/new", to: "corrections#new", as: "new_correction"
  get "corrections/:correction_hash_id", to: "corrections#show", as: "show_correction"
  get "corrections/:essay_hash_id/validate", to: "corrections#validate", as: "validate_correction"
  post "corrections/:essay_hash_id/", to: "corrections#create", as: "create_correction"
  get "corrections/:correction_hash_id/start", to: "corrections#start", as: "start_correction"
  patch "corrections/:correction_hash_id/", to: "corrections#update", as: "update_correction"
  post "corrections/:correction_hash_id/finish", to: "corrections#finish", as: "finish_correction"
  delete "corrections/:correction_hash_id/destroy", to: "corrections#destroy", as: "destroy_correction"

  # Correction Comments routes
  patch "corrections/:id/comment/update", to: "correction_comments#update", as: "update_correction_comment"
  delete "corrections/:id/comment/delete", to: "correction_comments#destroy", as: "destroy_correction_comment"

  # Credits routes
  get ":user_id/credits/refill", to: "credits#edit", as: "edit_credits"
  patch ":user_id/credits/refill", to: "credits#update", as: "update_credits"

  # Root
  root "sessions#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :students
    has_many :essays
    has_many :competences
    has_many :themes

    validates :description, :max_score, presence: true
    validates :max_score, numericality: { only_integer: true }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_login, :require_admin
  before_action :set_category, except: [:index, :new]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 16)
  end

  def show
    @competences = @category.competences.paginate(page: params[:page], per_page: 16)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path, success: "Categoria criada com sucesso"
    else
      render :new
    end
  end

  def edit
  end
  
  def update
    if @category.update(category_params)
      redirect_to categories_path, success: "Categoria alterada com sucesso"
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
  end

  private

  def category_params
    params.require(:category).permit(:description, :max_score)
  end

  def set_category
    @category = Category.find_by(id: params[:id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: @category, local: true, class: "d-flex flex-column") do |f| %>

<div class="form-group">
    <%= f.label :description, "Categoria:" %>
    <%= f.text_field :description, class: 'form-control', autocomplete: "off" %>
    <span class="text-danger"><%= @category.errors.messages[:description].first if @category.errors.any? %></span>
</div>

<div class="form-group">
    <%= f.label :max_score, "Pontuação Máxima:" %>
    <%= f.number_field :max_score, min:0 ,placeholder: 0, class: "form-control", autocomplete: "off" %>
    <span class="text-danger"><%= @category.errors.messages[:max_score].first if @category.errors.any? %></span>
</div>

<div class="form-group align-self-center">
    <%= f.button class: "btn btn-primary mr-2" do %>
     
    <span>Salvar</span>
    <% end %>
    
    <%= link_to categories_path, class: "btn btn-primary mr-2" do %>
    
    <span>Cancelar</span>
    <% end %>
</div>

<% end %>

<% if @category.errors.any? %>
<script>

    $(".form-group input, .form-group select").each(function () {
        $(this).removeClass("border-dark").addClass("border-danger");
    })

</script>
<% end %>

app/views/categories/edit.html.erb
<div class="row">
    <div class="col-md-12">
        <div class="card mb-3 text-dark shadow-sm">
            <div class="card-body">
                <h5 class="card-title">Editar Categoria</h5>
                <%= render  "form", category: @category %>
            </div>
        </div>
    </div>
</div>

app/views/categories/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card mb-3 text-dark shadow-sm">
      <div class="card-body">
        <div class="row mb-2">
          <div class="col-md-6 d-flex">
            <h5 class="card-title mb-0 align-self-center">Categorias</h5>
          </div>
          <div class="col-md-6 d-flex justify-content-end">
            <%= link_to new_category_path, class: "btn btn-link" do %>
            <span data-toggle="tooltip" data-placement="top" title="Nova Categoria">
              <%= fa_icon "plus" %>
            </span>
            <% end %>
          </div>
        </div>
        <div class="table-responsive-md">
          <table class="table table-bordered table-striped">
            <thead>
              <th style="width: 85%;">Descrição</th>
            </thead>
            <tbody>
              <% @categories.each do |category| %>
              <tr>
                <td class="align-middle"><%= category.description %></td>
                <td class="align-middle">
                  <%= link_to category_path(category), class: "btn btn-link" do %>
                  <span data-toggle="tooltip" data-placement="top" title="Ver Competências">
                    <%= fa_icon 'eye' %>
                  </span>
                  <% end %>
                  <%= link_to edit_category_path(category), class: "btn btn-link" do %>
                  <span data-toggle="tooltip" data-placement="top" title="Editar">
                    <%= fa_icon 'pencil-alt' %>
                  </span>
                  <% end %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>

        <%= will_paginate @category, list_classes: %w(pagination justify-content-center),
                                        next_label: "&#62;", previous_label: "&#60;"  %>
      </div>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<div class="row">
    <div class="col-md-12">
        <div class="card mb-3 text-dark shadow-sm">
            <div class="card-body">
                <h5 class="card-title">Nova Categoria</h5>
                <%= render  "form", category: @category %>
            </div>
        </div>
    </div>
</div>

app/views/categories/show.html.erb
<div class="row">
    <div class="col-md-12">
        <div class="card mb-3 text-dark shadow-sm">
            <div class="card-body">
                <div class="row mb-2">
                    <div class="col-md-6 d-flex">
                        <h5 class="card-title mb-0 align-self-center">Competências</h5>
                    </div>
                    <div class="col-md-6 d-flex justify-content-end">
                        <%= link_to new_competence_path(@category), class: "btn btn-link" do %>
                        <span data-toggle="tooltip" data-placement="top" title="Nova Competência">
                            <%= fa_icon "plus" %>
                        </span>
                        <% end %>
                    </div>
                </div>
                <div class="table-responsive-md">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <th style="width: 85%;">Competência</th>
                        </thead>
                        <tbody>
                            <% @competences.each do |competence| %>
                            <tr>
                                <td class="align-middle"><%= competence.description %></td>
                                <td class="align-middle">
                                    <!-- <%# link_to competence_path(@category,competence), class: "btn btn-link" do %>
                                    <span data-toggle="tooltip" data-placement="top" title="Ver Comentários">
                                        <%# fa_icon 'eye' %>
                                    </span>
                                    <%# end %> -->
                                    <%= link_to edit_competence_path(@category,competence), class: "btn btn-link" do %>
                                    <span data-toggle="tooltip" data-placement="top" title="Editar">
                                        <%= fa_icon 'pencil-alt' %>
                                    </span>
                                    <% end %>
                                </td>
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>

                <%= will_paginate @competences, list_classes: %w(pagination justify-content-center),
                                        next_label: "&#62;", previous_label: "&#60;"  %>
            </div>
        </div>
    </div>
</div>